# Rating Prediction Project

#### Data description

We have a client who has a website where people write different reviews for technical products.
Now they are adding a new feature to their website i.e. The reviewer will have to add stars(rating)
as well with the review. The rating is out 5 stars and it only has 5 options available 1 star, 2 stars,
3 stars, 4 stars, 5 stars. Now they want to predict ratings for the reviews which were written in the
past and they don’t have a rating. So, we have to build an application which can predict the rating
by seeing the review.
You have to scrape at least 20000 rows of data.
In this section you need to scrape the reviews of different laptops, Phones, Headphones, smart
watches, Professional Cameras, Printers, Monitors, Home theater, Router from different ecommerce websites.
Basically, we need these columns:  
1) reviews of the product.   
2) rating of the product.

After collecting the data, you need to build a machine learning model. Before model building we need to do
all data preprocessing steps involving NLP. Then try different models with different hyper parameters
and select the best model.

### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException

In [103]:
# initializing the driver to a variable

driver= webdriver.Chrome('chromedriver.exe')

### Scraping Reviews for Laptops

In [85]:
# Giving address to the driver

driver.get('https://www.flipkart.com/')

In [86]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('laptop')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [87]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
for i in page:
    pages.append(i.get_attribute('href'))

In [89]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [95]:
# Creating dataframe for the data.

laptop1= pd.DataFrame({"Review":review,"Rating":rating})
laptop1

                                                 Review Rating
0     Everything works with very fast speed due to i...      5
1     Good morning.\nIt is a nice product.\nI used i...      5
2     Flipkart just took 2 days to deliver the produ...      5
3     Got it 40k,and at that particular price it's j...      5
4     It's a best laptop in this price range. I have...      5
...                                                 ...    ...
1091                                   Completely happy      4
1092  I love it performance and great display,\n\nEx...      5
1093  Altogether it's a nice laptop only problem I f...      4
1094        Low battery backup,\nEverything works fine.      3
1095                                           Must buy      5

[1096 rows x 2 columns]

In [102]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [103]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('Laptop')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [51]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [53]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

Here we are extracting the reviews one by one for all ratings. this is because there is no rating displayed in text in the website.

In [58]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

laptop2=pd.concat([r1, r2,r3,r4,r5], axis=0)
laptop2

                                                Review Rating
0    We purchased a Lenovo Yoga 7 laptop and Touch-...      1
1                                                Worst      1
2    It has good touch screen and display. however,...      1
3    Worst product. Received 2 times defective lapt...      1
4    very slow, hang problem, updating of window ta...      1
..                                                 ...    ...
540  Just go for it Because its better than all the...      5
541  This latest (2021) 2 in 1 laptop from Dell is ...      5
542  Pros\nExcellent build quality\nGood screen wit...      5
543                                          Very nice      5
544  Wonderful product, it is really fast and smoot...      5

[1617 rows x 2 columns]

In [101]:
# Creating final dataframe for all the laptop reviews.

laptops=pd.concat([laptop1, laptop2], axis=0)
laptops

                                                 Review Rating
0     Everything works with very fast speed due to i...      5
1     Good morning.\nIt is a nice product.\nI used i...      5
2     Flipkart just took 2 days to deliver the produ...      5
3     Got it 40k,and at that particular price it's j...      5
4     It's a best laptop in this price range. I have...      5
...                                                 ...    ...
1612  Just go for it Because its better than all the...      5
1613  This latest (2021) 2 in 1 laptop from Dell is ...      5
1614  Pros\nExcellent build quality\nGood screen wit...      5
1615                                          Very nice      5
1616  Wonderful product, it is really fast and smoot...      5

[2713 rows x 2 columns]

In [105]:
#laptops.to_csv('laptopfinal.csv', index=False)

### Scraping Reviews for Phones

In [6]:
# Giving address to the driver

driver.get('https://www.flipkart.com/')

In [7]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('samsung s20')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [8]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
for i in page:
    pages.append(i.get_attribute('href'))

In [9]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,11):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [12]:
# Creating dataframe for the data.

phone1= pd.DataFrame({"Review":review,"Rating":rating})
phone1

                                                 Review Rating
0     The best phone I have purchased so far. The be...      5
1     The device gets heated up in just about anythi...      1
2     I upgraded to Sasung S20 after using Samsung S...      5
3     Easily the best compact phone with all the ess...      5
4     If there is any good thing that 2020 gave is S...      5
...                                                 ...    ...
1942                                        Ok but good      4
1943            superb.original product.thanks filpkart      5
1944  Best & awesome.😄 delivered well on time. get m...      5
1945                                         Good phone      4
1946                                      nice produced      5

[1947 rows x 2 columns]

In [40]:
# Giving another address to the driver

driver.get('https://www.ebay.com/')

In [41]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_id("gh-ac")
search_box.send_keys('phones')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_id("gh-btn").click()

In [42]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//div[@class='s-item__reviews']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [50]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    try:
        # Clicking on see all reviews.
        a= driver.find_element_by_xpath("//a[@class='see--all--reviews-link']")
        a.click()
        time.sleep(3)
        
        # scraping the data.   
        for j in range(3,7):
            for t in driver.find_elements_by_xpath("//div[@class='ebay-review-section-l']/div[1]"):
                rating.append(t.get_attribute('title').split( )[0])
        
            for r in driver.find_elements_by_xpath("//div[@class='ebay-review-section-r']/p[1]"):
                review.append(r.text)
            
            # Clicking on the next page.
            driver.find_element_by_xpath("//ul[@class='large pagination']/li[{}]".format(j)).click()
            time.sleep(3)

            
            
    except NoSuchElementException:
        pass

In [53]:
# Creating dataframe for the data.

phone2= pd.DataFrame({"Review":review,"Rating":rating})
phone2

                                                Review Rating
0    If you want the peak of Android right now, you...      5
1    The internal speaker and microphone did not wo...      2
2    The camera on this phone is much improved over...      5
3    Great phone with a few Google related glitches...      5
4    This replaces my Moto X4. The Pixel 3 is compa...      4
..                                                 ...    ...
517  Top of the line, form, function and dependabil...      5
518                                          love it !      5
519     The phone was new in sealed box as advertised.      5
520  Verified purchase:  Yes | Condition: Pre-Owned...      5
521  Excelente producto en muy buenas condiciones. ...      5

[522 rows x 2 columns]

In [63]:
# Removing rows that do not containt reviews.

phone2=phone2[phone2['Review'].str.contains('Sold by')==False]
phone2

                                                Review Rating
0    If you want the peak of Android right now, you...      5
1    The internal speaker and microphone did not wo...      2
2    The camera on this phone is much improved over...      5
3    Great phone with a few Google related glitches...      5
4    This replaces my Moto X4. The Pixel 3 is compa...      4
..                                                 ...    ...
516  Samsung galaxy s19plus g975 gsm factory unlock...      5
517  Top of the line, form, function and dependabil...      5
518                                          love it !      5
519     The phone was new in sealed box as advertised.      5
521  Excelente producto en muy buenas condiciones. ...      5

[500 rows x 2 columns]

In [27]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [28]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('phone')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [29]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [36]:
# Creating lists to store data

rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            time.sleep(2)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            time.sleep(2)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            time.sleep(2)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            time.sleep(2)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

Here we are extracting all the reviews other then 5 star reviews, as the majority of reviews collected before are of 5 star reviews.

In [37]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})

phone3=pd.concat([r1, r2,r3,r4], axis=0)
phone3

                                                Review  Rating
0    Both 13 MP and 5MP Camera quality is good. Hav...       1
1    Battery is getting drained out quite fast. 7% ...       1
2    Compass is not working, showing error as requi...       1
3    Review after one-day full usage and 28 days of...       1
4    Made in china...The country of origin should b...       1
..                                                 ...     ...
734                         Overheating issue is there       4
735                           Camera Clarity is good..       4
736  Dnt come expecting too much. It's an standard ...       4
737  Awesome 😎\nSuper mobile and best calling charg...       4
738                                      It looks good       4

[3141 rows x 2 columns]

In [40]:
# Creating final dataframe for all the phones reviews.

phones=pd.concat([phone1, phone2, phone3], axis=0)
phones

                                                Review  Rating
0    The best phone I have purchased so far. The be...       5
1    The device gets heated up in just about anythi...       1
2    I upgraded to Sasung S20 after using Samsung S...       5
3    Easily the best compact phone with all the ess...       5
4    If there is any good thing that 2020 gave is S...       5
..                                                 ...     ...
734                         Overheating issue is there       4
735                           Camera Clarity is good..       4
736  Dnt come expecting too much. It's an standard ...       4
737  Awesome 😎\nSuper mobile and best calling charg...       4
738                                      It looks good       4

[5588 rows x 2 columns]

In [42]:
#phones.to_csv('phonefinal.csv', index=False)

### Scraping Reviews for Headphones

In [103]:
# Giving an address to the driver

driver.get('https://www.shopclues.com/')

In [104]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('autocomplete')
search_bar.send_keys('headphone')
time.sleep(5)

# clicking on the search button.

driver.find_element_by_xpath("//a[@class='srch_action btn orange']").click()

In [105]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//div[@class='column col3 search_blocks']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [113]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(4)
    try:
        a= driver.find_element_by_id("moreReview")
        for j in range(0,6):
            try:
                a.click()
                time.sleep(2)
            except ElementNotInteractableException:
                pass
            
        for t in driver.find_elements_by_xpath("//div[@class='r_comm_info']/div[1]/span[1]"):
            rating.append(t.text)
        
        for r in driver.find_elements_by_xpath("//div[@class='review_desc']/p[1]"):
            review.append(r.text)
            

    except NoSuchElementException:
        pass

In [116]:
# Creating dataframe for the data.

headphone1= pd.DataFrame({"Review":review,"Rating":rating})
headphone1

                                                Review Rating
0                                    Voice cut hote he      5
1                                                 nice      4
2                      Same one headset is not working      2
3                                Mic is not upto level      2
4                  The product is not working properly      2
..                                                 ...    ...
493  very cheap quality Fraud h San Kuch Jo is per ...      1
494  dhis is not connecting my devaic 000 bed parfo...      1
495                                    Product quality      2
496                           One earphone not working      2
497                      One Side Not Working Properly      4

[498 rows x 2 columns]

In [131]:
# Giving another address to the driver

driver.get('https://www.myntra.com/')

In [132]:
# Finding element for search bar and giving value to it.

search_bar= driver.find_element_by_xpath("//input[@class='desktop-searchBar']")
search_bar.send_keys('headphone')
time.sleep(2)

# clicking on the search button.

driver.find_element_by_xpath("//a[@class='desktop-submit']").click()

In [133]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//li[@class='product-base']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [ ]:
pages= pages[0:20]

In [136]:
# Creating lists to store data

review=[]
rating=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    driver.find_element_by_xpath("//a[@class='detailed-reviews-allReviews']").click()
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[6]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-fiveStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[7]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-fourStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[8]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-threeStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[9]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-twoStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[10]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-oneStar']"):
            rating.append(t.text)
        
    except NoSuchElementException:
        pass

In [139]:
# Creating dataframe for the data.

headphone2= pd.DataFrame({"Review":review,"Rating":rating})
headphone2

                                                Review Rating
0    That's amazing from the boat, I really love it...      5
1                            Bass is gd.....gd product      5
2    Pure sound quality. Pure bass but because of t...      5
3    It's very nice , sound quality is also good an...      5
4                                            Very good      5
..                                                 ...    ...
897                       Left is not working properly      1
898                       Statistics in while speaking      1
899              Wrost one please don't waste ur money      1
900  Hey Guys, Getting Damaged Products. Please Don...      1
901  Quick touch is not working it's been 3 days an...      1

[902 rows x 2 columns]

In [8]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [9]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('headphone')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [10]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [22]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [19]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

headphone3=pd.concat([r1,r2,r3,r4,r5], axis=0)
headphone3

                                                Review  Rating
0     Uncomfortable ear fit, device did not disconn...       1
1    Right side EARBUD is completely not working. I...       1
2    First time delivered product has the charging ...       1
3    Pros.\n1. Packaging\n2. Light weight\n3. Sound...       1
4    These are not getting disconnected after keepi...       1
..                                                 ...     ...
762  This headphone is value for money ..& its look...       5
763           liked the product . had expected quality       5
764                                          Very good       5
765                         Sound quality is Best... 🙂       5
766                                         Super..😀😀😀       5

[4365 rows x 2 columns]

In [24]:
# Creating final dataframe for all the headphone reviews.

headphones=pd.concat([headphone1, headphone2, headphone3], axis=0)
headphones

                                                Review  Rating
0                                    Voice cut hote he       5
1                                                 nice       4
2                      Same one headset is not working       2
3                                Mic is not upto level       2
4                  The product is not working properly       2
..                                                 ...     ...
762  This headphone is value for money ..& its look...       5
763           liked the product . had expected quality       5
764                                          Very good       5
765                         Sound quality is Best... 🙂       5
766                                         Super..😀😀😀       5

[5765 rows x 2 columns]

In [25]:
#headphones.to_csv('headphonefinal.csv', index=False)

### Scraping reviews for smart watch

In [47]:
# Giving address to the driver

driver.get('https://www.flipkart.com/')

In [48]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('smart watch')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [49]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
for i in page:
    pages.append(i.get_attribute('href'))

In [52]:
pages=pages[0:11]

In [86]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [61]:
# Creating dataframe for the data.

smartwatch1= pd.DataFrame({"Review":review,"Rating":rating})
smartwatch1

                                                Review Rating
0    Writing this review after 2 weeks.\nPROS:-less...      4
1    Wooww🖤Grt watch\nawesome 💌💌\n🖤I loved it super...      5
2    Ya its a cool watch and I liked the built qual...      4
3    Boat smart watch nice and decent product in th...      4
4    Watch is amazing. Looks so good & battery is g...      5
..                                                 ...    ...
625  SAMSUNG Active 2 44 mm with Super AMOLED displ...      5
626  One of the best smart watch in the market .. H...      5
627  If you want to buy this watch it is a value fo...      4
628  Got my watch on 31st august.Charged it to 100 ...      5
629  After a long research I got this beauty. It ha...      5

[630 rows x 2 columns]

In [90]:
# Giving another address to the driver

driver.get('https://www.myntra.com/')

In [91]:
# Finding element for search bar and giving value to it.

search_bar= driver.find_element_by_xpath("//input[@class='desktop-searchBar']")
search_bar.send_keys('smart watch')
time.sleep(2)

# clicking on the search buton.

driver.find_element_by_xpath("//a[@class='desktop-submit']").click()

In [92]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//li[@class='product-base']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [131]:
pages=pages[0:15]

In [132]:
# Creating lists to store data

review=[]
rating=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    
    # Scraping reviews for 5 stars ratings.
    try:
        driver.find_element_by_xpath("//a[@class='detailed-reviews-allReviews']").click()
        time.sleep(3)
        
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[6]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-fiveStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[7]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-fourStars']"):
            rating.append(t.text)
            
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[8]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-threeStars']"):
            rating.append(t.text)
        
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[9]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
            
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-twoStars']"):
            rating.append(t.text)
         
        driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
        
    except NoSuchElementException:
        pass
    
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//span[@class='myntraweb-sprite dropdown-filter-arrowIcon sprites-reviewFilterDropdownArrow']")
        a.click()
        time.sleep(2)
        b=driver.find_element_by_xpath("//div[@class='dropdown-filter-dropdown dropdown-filter-open']/div[10]/span[1]")
        b.click()
        time.sleep(3)
        
        for _ in range(10):
            driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
            
        time.sleep(2)
        for r in driver.find_elements_by_xpath("//div[@class='user-review-reviewTextWrapper']"):
            review.append(r.text)
        
        for t in driver.find_elements_by_xpath("//span[@class='user-review-starRating user-review-oneStar']"):
            rating.append(t.text)
        time.sleep(2)
    except NoSuchElementException:
        pass

In [164]:
# Creating dataframe for the data.

smartwatch2= pd.DataFrame({"Review":review,"Rating":rating})
smartwatch2

                                                Review Rating
0    I have been using this for a month now. This i...      5
1    Just bought the phone. Pairing was easy Qualit...      5
2    Its awasam and very comfortable. Corns -- 1.in...      5
3    Just giving review based on its look as i just...      5
4    Loved very much ❣️ .. thank u myntra ✨✨✨✨. Ver...      5
..                                                 ...    ...
417                                       Good looking      4
418                                          I m happy      4
419                                               Nicw      4
420  1) Uncomfortable to wear because strip has to ...      3
421  The product has good precision but there is a ...      3

[422 rows x 2 columns]

In [3]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [4]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('smartwatch')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [5]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [7]:
pages= pages[0:16]

In [17]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [18]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

smartwatch3=pd.concat([r1,r2,r3,r4,r5], axis=0)
smartwatch3

                                                Review  Rating
0    BP Measurement is way different from a standar...       1
1    I have been using samsung S2 and then honor ma...       1
2    I am very much disappointed from this product....       1
3    I purchased it to monitor blood pressure frequ...       1
4    This product is absolutely overrated... Very l...       1
..                                                 ...     ...
241  Really loved this watch. Oxygen pressure is ap...       5
242  Using this from more than a week now.\nMust sa...       5
243  Pros\n1. Big display\n2. Bluetooth connectivit...       5
244  This is the perfect watch I was looking for as...       5
245  An amazing smartwatch at a decent price, it ha...       5

[1205 rows x 2 columns]

In [20]:
# Creating final dataframe for all the smartwatch reviews.

smartwatches=pd.concat([smartwatch1, smartwatch2, smartwatch3], axis=0)
smartwatches

                                                Review  Rating
0    Writing this review after 2 weeks.\nPROS:-less...       4
1    Wooww🖤Grt watch\nawesome 💌💌\n🖤I loved it super...       5
2    Ya its a cool watch and I liked the built qual...       4
3    Boat smart watch nice and decent product in th...       4
4    Watch is amazing. Looks so good & battery is g...       5
..                                                 ...     ...
241  Really loved this watch. Oxygen pressure is ap...       5
242  Using this from more than a week now.\nMust sa...       5
243  Pros\n1. Big display\n2. Bluetooth connectivit...       5
244  This is the perfect watch I was looking for as...       5
245  An amazing smartwatch at a decent price, it ha...       5

[2257 rows x 2 columns]

In [21]:
#smartwatches.to_csv('smartwatchfinal.csv', index=False)

### Scraping reviews for Professional Cameras.

In [24]:
# Giving an address to the driver

driver.get('https://www.ebay.com/')

In [31]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_id("gh-ac")
search_box.send_keys('professional camera')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_id("gh-btn").click()

In [36]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//div[@class='s-item__reviews']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [40]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        a= driver.find_element_by_xpath("//a[@class='see--all--reviews-link']")
        a.click()
        time.sleep(3)
        
            
        for j in range(3,12):
            for t in driver.find_elements_by_xpath("//div[@class='ebay-review-section-l']/div[1]"):
                rating.append(t.get_attribute('title').split( )[0])
        
            for r in driver.find_elements_by_xpath("//div[@class='ebay-review-section-r']/p[1]"):
                review.append(r.text)
            
            driver.find_element_by_xpath("//ul[@class='large pagination']/li[{}]".format(j)).click()
            time.sleep(3)

            
            
    except NoSuchElementException:
        pass

In [41]:
# Creating dataframe for the data.

camera1= pd.DataFrame({"Review":review,"Rating":rating})
camera1

                                                Review Rating
0    An excellent example of a three digit (D100, D...      5
1    The D200 is an excellent camera for being an o...      5
2    This has a CCD sensor. The colors are brighter...      5
3    Even though the rest of the world seemed to be...      5
4    This camera is a very well built and feels sub...      5
..                                                 ...    ...
533  Forget it!  Uses obsolete, impossible to find ...      1
534  Was as described and was top of the line in it...      5
535  This replaces an identical camera that was sto...      5
536  i bought it broken.took about 6hrs to fix.work...      3
537  i bought it broken.took about 6hrs to fix.work...      3

[538 rows x 2 columns]

In [2]:
# Removing rows that do not containt reviews.

camera1= camera1[camera1["Review"].str.contains("Verified purchase:")==False]

In [23]:
# Giving another address to the driver

driver.get('https://www.flipkart.com/')

In [24]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('professional camera')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [25]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='s1Q9rs']")
for i in page:
    pages.append(i.get_attribute('href'))

In [26]:
pages= pages[0:20]

In [27]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [44]:
# Creating dataframe for the data.

camera2= pd.DataFrame({"Review":review,"Rating":rating})
camera2

                                                 Review Rating
0     After using for a short period of time, it giv...      5
1     Best camara at this price point and sony have ...      5
2     Pros:\n1. Features/Price in Camera body\n2. EV...      3
3     I was owning D5100 and was thinking to upgrade...      5
4     I was more reviewed after purchased this camer...      4
...                                                 ...    ...
1095  Can't be compared with Canon and Nikon product...      5
1096                               really superb camera      5
1097  Fantastick camera, specifically autofocus and ...      5
1098  The product is not good for photography purpos...      3
1099  Received in very good condition. Delivery reas...      5

[1100 rows x 2 columns]

In [48]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [49]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('professional cameras')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [50]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [53]:
pages= pages[0:16]

In [55]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [57]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

camera3=pd.concat([r1,r2,r3,r4,r5], axis=0, ignore_index=True)
camera3

                                                 Review  Rating
0     You are on your own if you buy this product be...       1
1     Request for replacement of camera main body Th...       1
2     Canon Has Cheated The entire photography commu...       1
3     I paid Rs 20240 for this product and have read...       1
4     The camera is in good condition...I have recei...       1
...                                                 ...     ...
2372                                    Value for money       5
2373       This is the perfect camera for videographers       5
2374                                          Excellent       5
2375  Light and easy to carry around. Comes with a g...       5
2376  Free V-Log L Profile is very helpful in pro co...       5

[2377 rows x 2 columns]

In [7]:
# Creating final dataframe for all the camera reviews.

cameras=pd.concat([camera1, camera2, camera3], axis=0, ignore_index=True)
cameras

                                                 Review  Rating
0     An excellent example of a three digit (D100, D...       5
1     The D200 is an excellent camera for being an o...       5
2     This has a CCD sensor. The colors are brighter...       5
3     Even though the rest of the world seemed to be...       5
4     This camera is a very well built and feels sub...       5
...                                                 ...     ...
4010                                    Value for money       5
4011       This is the perfect camera for videographers       5
4012                                          Excellent       5
4013  Light and easy to carry around. Comes with a g...       5
4014  Free V-Log L Profile is very helpful in pro co...       5

[3959 rows x 2 columns]

In [61]:
#cameras.to_csv('camerafinal.csv', index=False)

### Scraping reviews for printers

In [3]:
# Giving address to the driver

driver.get('https://www.flipkart.com/')

In [4]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('printer')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [5]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='s1Q9rs']")
for i in page:
    pages.append(i.get_attribute('href'))

In [7]:
pages= pages[0:20]

In [12]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [11]:
# Creating dataframe for the data.

printer1= pd.DataFrame({"Review":review,"Rating":rating})
printer1

                                                 Review Rating
0     Please Don't Install It On Your Own. Call Epso...      4
1     Excellent delivery, rather superfast. Thank yo...      5
2     Definetly Much better than HP . Must buy . Col...      2
3     The printer works very nice.its printing speed...      5
4     Best quality and also ink does not spoil over ...      5
...                                                 ...    ...
1501            So beautiful item thanks again flipkart      5
1502                                     Hp is the best      5
1503  Product is not good. It doesn't print page as ...      2
1504                                   color ink leaked      1
1505                                          Very good      5

[1506 rows x 2 columns]

In [33]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [34]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('printer')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [35]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [36]:
pages= pages[0:13]

In [37]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//li[@class='a-last']/a[1]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//li[@class='a-last']/a[1]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//li[@class='a-last']/a[1]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//li[@class='a-last']/a[1]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//li[@class='a-last']/a[1]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [38]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

printer2=pd.concat([r1,r2,r3,r4,r5], axis=0, ignore_index=True)
printer2

                                                 Review  Rating
0     I won't recommend this. Hardly it worked, it's...       1
1     Printer catridge 805 not available anywhere in...       1
2     Waste of money. Because I had printed around 7...       1
3     A very bad product. I can't imagine HP is sell...       1
4     Worst printer. Just to check, gave a print for...       1
...                                                 ...     ...
2841  Excellent product, top notch..print quality is...       5
2842                Best printer in this price segment.       5
2843                                       Best product       5
2844                          everything simple in this       5
2845                                       Good quality       5

[2846 rows x 2 columns]

In [45]:
# Creating final dataframe for all the printer reviews.

printers=pd.concat([printer1, printer2], axis=0, ignore_index=True)
printers

                                                 Review Rating
0     Please Don't Install It On Your Own. Call Epso...      4
1     Excellent delivery, rather superfast. Thank yo...      5
2     Definetly Much better than HP . Must buy . Col...      2
3     The printer works very nice.its printing speed...      5
4     Best quality and also ink does not spoil over ...      5
...                                                 ...    ...
4347  Excellent product, top notch..print quality is...      5
4348                Best printer in this price segment.      5
4349                                       Best product      5
4350                          everything simple in this      5
4351                                       Good quality      5

[4352 rows x 2 columns]

In [46]:
#printers.to_csv('printerfinal.csv', index=False)

### Scraping reviews for Monitors

In [63]:
# Giving an address to the driver

driver.get('https://www.flipkart.com/')

In [64]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('monitor')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [69]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
for i in page:
    pages.append(i.get_attribute('href'))

In [71]:
pages= pages[0:16]

In [72]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [73]:
# Creating dataframe for the data.

monitor1= pd.DataFrame({"Review":review,"Rating":rating})
monitor1

                                                 Review Rating
0     This is the good one which I have choose from ...      4
1     Best Product at this price point. I got a defe...      5
2     Bought this for 10k. The delivery was amazing....      5
3                               Best price Best quality      5
4     Except Sound Issues test everything is Good an...      5
...                                                 ...    ...
1066  Thank you HP, such a wonderful monitor with in...      5
1067  Nice and bright panle but I was expecting more...      5
1068  Very sencitive, be careful while setup and mov...      4
1069                 Excellent monitor. Value for money      5
1070                         Good but little bit costly      4

[1071 rows x 2 columns]

In [87]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [88]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('monitor')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [89]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [90]:
pages= pages[0:13]

In [94]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,7):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [95]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

monitor2=pd.concat([r1,r2,r3,r4,r5], axis=0, ignore_index=True)
monitor2

                                                 Review  Rating
0     Please do not purchase this Lenovo Monitor, fa...       1
1     Do not buy this monitor simply it’s waste of m...       1
2     The inbuilt sound is not working, and lenovo c...       1
3     Monitor display turns blue with lines. Worst c...       1
4     Please don't get impressed by the advertisemen...       1
...                                                 ...     ...
2795  Very good monitor in this price range.\nGot it...       5
2796  Best of volume quality\nResolution awsmm..\nSu...       5
2797  Second LG monitor, the 1st one (ev22) lasted 9...       5
2798  Design is very elegant, slim bezels, modern.\n...       5
2799  Everything's fine but the display brightness d...       5

[2800 rows x 2 columns]

In [97]:
# Creating final dataframe for all the monitor reviews.

monitors=pd.concat([monitor1, monitor2], axis=0, ignore_index=True)
monitors

                                                 Review Rating
0     This is the good one which I have choose from ...      4
1     Best Product at this price point. I got a defe...      5
2     Bought this for 10k. The delivery was amazing....      5
3                               Best price Best quality      5
4     Except Sound Issues test everything is Good an...      5
...                                                 ...    ...
3866  Very good monitor in this price range.\nGot it...      5
3867  Best of volume quality\nResolution awsmm..\nSu...      5
3868  Second LG monitor, the 1st one (ev22) lasted 9...      5
3869  Design is very elegant, slim bezels, modern.\n...      5
3870  Everything's fine but the display brightness d...      5

[3871 rows x 2 columns]

In [98]:
#monitors.to_csv('monitorfinal.csv', index=False)

### Scraping reviews for Home theatre

In [100]:
# Giving an address to the driver

driver.get('https://www.ebay.com/')

In [101]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_id("gh-ac")
search_box.send_keys('home theatre')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_id("gh-btn").click()

In [102]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//div[@class='s-item__reviews']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [105]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        a= driver.find_element_by_xpath("//a[@class='see--all--reviews-link']")
        a.click()
        time.sleep(3)
        
            
        for j in range(3,12):
            for t in driver.find_elements_by_xpath("//div[@class='ebay-review-section-l']/div[1]"):
                rating.append(t.get_attribute('title').split( )[0])
        
            for r in driver.find_elements_by_xpath("//div[@class='ebay-review-section-r']/p[1]"):
                review.append(r.text)
            
            driver.find_element_by_xpath("//ul[@class='large pagination']/li[{}]".format(j)).click()
            time.sleep(3)

            
            
    except NoSuchElementException:
        pass

In [108]:
# Creating dataframe for the data.

hometheatre1= pd.DataFrame({"Review":review,"Rating":rating})
hometheatre1

                                                Review Rating
0    This used receiver works GREAT. Easy set up. T...      5
1    This is my first tru Home Theater System with ...      5
2    The system SONY BD VE300 is Great the best eve...      5
3    The stereo is a really nice unit the only prob...      4
4    I bought this system for a couple of reasons, ...      5
..                                                 ...    ...
169  This thing rocks! So many features I'm still f...      5
170  liked the idea of wireless speakers\ndid not l...      1
171  love the sound but felt decieved because it wa...      3
172  I bought this for my husband's birthday,and he...      5
173                                              great      5

[174 rows x 2 columns]

In [8]:
# Removing rows that do not containt reviews.

hometheatre1= hometheatre1[hometheatre1["Review"].str.contains("Verified purchase:")==False]

In [3]:
# Giving another address to the driver

driver.get('https://www.flipkart.com/')

In [4]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
search_box.send_keys('home theatre')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()

In [7]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//a[@class='s1Q9rs']")
for i in page:
    pages.append(i.get_attribute('href'))

In [9]:
pages= pages[0:11]

In [13]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        # Clicking on view all review.
        a=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
        a.click()
        time.sleep(3)
        
        # Clicking on the read more options to display entire text.
        for j in driver.find_elements_by_xpath("//span[@class='_1BWGvX']"):
            j.click()
        
        # Scraping data.
        for k in range(0,12):
            for t in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div"):
                rating.append(t.text)
            for r in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
                review.append(r.text)
                
            # Clicking o the next button.
            driver.find_element_by_xpath("//span[contains(text(),'Next')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass

In [11]:
# Creating dataframe for the data.

hometheatre2= pd.DataFrame({"Review":review,"Rating":rating})
hometheatre2

                                                Review Rating
0    Excellent product in budget .i m loving it.i p...      5
1    Nice product. Bluetooth connectivity are very ...      5
2    Writing this review after using 4 days.. No do...      4
3    Its good in this price range but if you are lo...      4
4    Completely mind blowing speaker more than my e...      5
..                                                 ...    ...
585                                               Good      4
586               Very good product sound quality best      5
587          Not bad... Better for pc or small room...      3
588                                   Very good prodac      5
589                                      Good speakers      5

[590 rows x 2 columns]

In [14]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [15]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('home theatre')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [16]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [19]:
pages= pages[0:11]

In [27]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,5):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,5):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,9):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,9):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,6):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [28]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

hometheatre3=pd.concat([r1,r2,r3,r4,r5], axis=0, ignore_index=True)
hometheatre3

                                                 Review  Rating
0     Don't buy its no worth for money customer care...       1
1                                  Send damage products       1
2                       Vest of money not good product.       1
3     Worst product... Cheaters.... It got repair wi...       1
4     Damage product recieve.... Bad quality product...       1
...                                                 ...     ...
2611                                Sound quality super       5
2612                                     Sound not good       5
2613  The best one in the class. Surround sound syst...       5
2614  very good sound quality. at this price range (...       5
2615  Audio fills a normal Hall of 15x15 sft.\nQuali...       5

[2616 rows x 2 columns]

In [11]:
# Creating final dataframe for all the home theatre reviews.

hometheatres=pd.concat([hometheatre1,hometheatre2, hometheatre3], axis=0, ignore_index=True)
hometheatres

                                                 Review  Rating
0     This used receiver works GREAT. Easy set up. T...       5
1     This is my first tru Home Theater System with ...       5
2     The system SONY BD VE300 is Great the best eve...       5
3     The stereo is a really nice unit the only prob...       4
4     I bought this system for a couple of reasons, ...       5
...                                                 ...     ...
3375                                Sound quality super       5
3376                                     Sound not good       5
3377  The best one in the class. Surround sound syst...       5
3378  very good sound quality. at this price range (...       5
3379  Audio fills a normal Hall of 15x15 sft.\nQuali...       5

[3366 rows x 2 columns]

In [33]:
#hometheatres.to_csv('hometheatrefinal.csv', index=False)

### Scraping reviews for routers

In [88]:
# Giving an address to the driver

driver.get('https://www.ebay.com/')

In [89]:
# Finding element for the search bar and giving value inside it.

search_box= driver.find_element_by_id("gh-ac")
search_box.send_keys('routers')
time.sleep(2)

# Clicking on the search buton

driver.find_element_by_id("gh-btn").click()

In [90]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//div[@class='s-item__reviews']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [91]:
pages= pages[1:16]

In [92]:
# creating lists to store data.

rating=[]
review=[]

# Scraping the Ratings and reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    try:
        a= driver.find_element_by_xpath("//a[@class='see--all--reviews-link']")
        a.click()
        time.sleep(3)
        
            
        for j in range(3,12):
            for t in driver.find_elements_by_xpath("//div[@class='ebay-review-section-l']/div[1]"):
                rating.append(t.get_attribute('title').split( )[0])
        
            for r in driver.find_elements_by_xpath("//div[@class='ebay-review-section-r']/p[1]"):
                review.append(r.text)
            
            driver.find_element_by_xpath("//ul[@class='large pagination']/li[{}]".format(j)).click()
            time.sleep(3)

            
            
    except NoSuchElementException:
        pass

In [99]:
# Creating dataframe for the data.

router1= pd.DataFrame({"Review":review,"Rating":rating})
router1

                                                Review Rating
0    I bought this to use as an access point.  I am...      5
1     It doesn't boost wifi. Wifi is the same with it!      2
2    Local new cable co. Put in new router said wou...      5
3    I feel like this is the best extender out ther...      5
4    Configured as a bridge on my network.  Perform...      4
..                                                 ...    ...
705  Verified purchase:  Yes | Condition: Pre-Owned...      3
706                                     It's very good      5
707                                        works great      5
708                   Very satisfied with the purchase      5
709                                  Perfect product.       5

[710 rows x 2 columns]

In [102]:
# Removing rows that do not containt reviews.

router1= router1[router1["Review"].str.contains("Verified purchase:")==False]
router1

                                                Review Rating
0    I bought this to use as an access point.  I am...      5
1     It doesn't boost wifi. Wifi is the same with it!      2
2    Local new cable co. Put in new router said wou...      5
3    I feel like this is the best extender out ther...      5
4    Configured as a bridge on my network.  Perform...      4
..                                                 ...    ...
704  T-mobile ruined a good router.  Tethers to hot...      2
706                                     It's very good      5
707                                        works great      5
708                   Very satisfied with the purchase      5
709                                  Perfect product.       5

[676 rows x 2 columns]

In [104]:
# Giving another address to the driver

driver.get('https://www.amazon.in/')

In [105]:
# Finding element for search bar and giving value in it.

search_bar= driver.find_element_by_id('twotabsearchtextbox')
search_bar.send_keys('router')
time.sleep(2)

# Clicking on the search button

driver.find_element_by_id('nav-search-submit-button').click()

In [106]:
# Extracting page urls of all the products.

pages=[]
page= driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
for i in page:
    pages.append(i.get_attribute('href'))

In [108]:
pages=pages[0:10]

In [110]:
# Creating lists to store data

rev5=[]
rev4=[]
rev3=[]
rev2=[]
rev1=[]

# Scraping the reviews.

for i in pages:
    driver.get(i)
    time.sleep(3)
    
    # Scraping reviews for 5 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 5star']")
        a.click()
        time.sleep(3)
        for j in range(0,4):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span[1]"):
                rev5.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
                
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 4 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 4star']")
        a.click()
        time.sleep(3)
        for j in range(0,4):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev4.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 3 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 3star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev3.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 2 stars ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 2star']")
        a.click()
        time.sleep(3)
        for j in range(0,8):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev2.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass
    
    # Scraping reviews for 1 star ratings.
    try:
        a=driver.find_element_by_xpath("//a[@class='a-link-normal 1star']")
        a.click()
        time.sleep(3)
        for j in range(0,5):
            for r in driver.find_elements_by_xpath("//span[@class='a-size-base review-text review-text-content']/span"):
                rev1.append(r.text)
            driver.find_element_by_xpath("//a[contains(text(),'Next page')]").click()
            time.sleep(3)
        
    except NoSuchElementException:
        pass

In [111]:
# Creating dataframes and concatenating them.

r1= pd.DataFrame({"Review":rev1,"Rating":1})
r2= pd.DataFrame({"Review":rev2,"Rating":2})
r3= pd.DataFrame({"Review":rev3,"Rating":3})
r4= pd.DataFrame({"Review":rev4,"Rating":4})
r5= pd.DataFrame({"Review":rev5,"Rating":5})

router2=pd.concat([r1,r2,r3,r4,r5], axis=0, ignore_index=True)
router2

                                                 Review  Rating
0     Amazon has delivered an used/returned product....       1
1     It is not even giving the coverage of 15 feet ...       1
2     Ordered RV340 on 6th Jan 2021. It's dead on 18...       1
3     Absolutely no support from Cisco to set it up\...       1
4                                         Not satisfied       1
...                                                 ...     ...
1832                       Good router. Good bandwidth.       5
1833  Most advanced version Modem with many addition...       5
1834                                horribly good...!!!       5
1835                                         👍❤️👍👍super       5
1836                 Good Product and easy to installed       5

[1837 rows x 2 columns]

In [112]:
# Creating final dataframe for all the Router reviews.

routers=pd.concat([router1,router2], axis=0, ignore_index=True)
routers

                                                 Review Rating
0     I bought this to use as an access point.  I am...      5
1      It doesn't boost wifi. Wifi is the same with it!      2
2     Local new cable co. Put in new router said wou...      5
3     I feel like this is the best extender out ther...      5
4     Configured as a bridge on my network.  Perform...      4
...                                                 ...    ...
2508                       Good router. Good bandwidth.      5
2509  Most advanced version Modem with many addition...      5
2510                                horribly good...!!!      5
2511                                         👍❤️👍👍super      5
2512                 Good Product and easy to installed      5

[2513 rows x 2 columns]

In [113]:
#routers.to_csv('routerfinal.csv', index=False)

In [16]:
# Loading all the scraped data.

laptops= pd.read_csv('laptopfinal.csv')
phones= pd.read_csv('phonefinal.csv')
headphones= pd.read_csv('headphonefinal.csv')
smartwatches= pd.read_csv('smartwatchfinal.csv')
cameras= pd.read_csv('camerafinal.csv')
printers= pd.read_csv('printerfinal.csv')
monitors= pd.read_csv('monitorfinal.csv')
hometheatres= pd.read_csv('hometheatrefinal.csv')
routers= pd.read_csv('routerfinal.csv')

In [19]:
# Creating the final dataframe containing all the data.

df=pd.concat([laptops,phones,headphones,smartwatches,cameras,printers,monitors,hometheatres,routers], axis=0, ignore_index=True)
df

                                                  Review  Rating
0      Everything works with very fast speed due to i...       5
1      Good morning.\nIt is a nice product.\nI used i...       5
2      Flipkart just took 2 days to deliver the produ...       5
3      Got it 40k,and at that particular price it's j...       5
4      It's a best laptop in this price range. I have...       5
...                                                  ...     ...
34379                       Good router. Good bandwidth.       5
34380  Most advanced version Modem with many addition...       5
34381                                horribly good...!!!       5
34382                                         👍❤️👍👍super       5
34383                 Good Product and easy to installed       5

[34384 rows x 2 columns]

In [20]:
#df.to_csv('reviewsfinal.csv', index=False)

In [21]:
# Saving the data as an excel sheet.

df.to_excel("finalreview.xlsx")